version: 0.2

phases:
  #pre_build:
   # commands:
    #  - $(aws ecr get-login --region us-east-1 --no-include-email )
     # - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/test_springboot.jar
  discard-paths: yes