student:
  name: dicey
  age: 22
spring:
  datasource:
    url: jdbc:mysql://springboot-aurora.cwv8pqm4jp8m.rds.cn-northwest-1.amazonaws.com.cn:3306/aws_demo?useUnicode=true&characterEncoding=gbk&zeroDateT
    username: aws_demo
    password: aws_demo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
server:
  address: 0.0.0.0
#  8080端口要备案
  port: 1234